[workspace]
resolver = "3"
members = ["rapidrand", "rapidrand-bench", "rapidrand-cat"]

[workspace.dependencies]
rapidrand = { path = "rapidrand", default-features = false }

# aggressive optimizations for benchmark consistency
[profile.release]
codegen-units = 1
lto = "fat"
incremental = false
opt-level = 3

# aggressive optimizations for benchmark consistency
[profile.bench]
codegen-units = 1
lto = "fat"
incremental = false
opt-level = 3
debug = false
debug-assertions = false
strip = true

[workspace.lints.rust]
unused_must_use = "deny"
